
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Devang Chhajed
 */
public class Order extends javax.swing.JFrame {
   String serial,cname,keyboard,monitor,mouse,printer,pro,ram,hd,graphiccard;
    

    public class values 
    {
         
    
    }
    
    public Order() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SrNo.", "Company", "Monitor", "Keyboard", "Mouse", "Processor", "RAM", "HD", "GC", "Printer"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 830, 300));

        jButton1.setText("View Orders");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 250, 40));

        jButton2.setText("Update Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 190, 40));

        jButton3.setText("Delete Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 180, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

   DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();    
   
   
       int temp_no=tm.getRowCount();
        for(int i=temp_no;i>=1;i--)
          {
            tm.removeRow(0);
               
           } 
            jTable1.setModel(tm);
            
            
            
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/technocomputer","root","manager");
Statement s=con.createStatement();
String q= "select * from orders";
ResultSet rs=s.executeQuery(q);
while(rs.next())
{int srno=rs.getInt("SrNO");
    String cname=rs.getString("cname");
String Pro=rs.getString("Pro");
 String RAM=rs.getString("RAM");
 String HD=rs.getString("HD");
 String GC=rs.getString("graphiccard");
String Monitor=rs.getString("Monitor");
String Keyboard=rs.getString("Keyboard");
String Printer=rs.getString("Printer");
String Mouse=rs.getString("Mouse");



 tm.addRow(new Object[]{srno,cname,Monitor,Keyboard,Mouse,Pro,RAM,HD,GC,Printer});
}
     
}catch(Exception e){
JOptionPane.showMessageDialog(null,e);}    
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String sno=JOptionPane.showInputDialog("Enter Your Order's serial No..");
       EditOrder eo=new EditOrder();
        Order or=new Order();
      try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/technocomputer","root","manager");
            Statement s=con.createStatement();
            String q= "select * from orders where srno="+sno;
            ResultSet rs=s.executeQuery(q);
            
                or.serial=rs.getString(1);
                 or.cname=rs.getString(2);
                 or.keyboard = rs.getString(4);   
                 or.monitor = rs.getString(3);
                 or.mouse = rs.getString(5);
                 or.printer =rs.getString(10);
                 or.pro=rs.getString(8);
                 or.ram=rs.getString(6);
                 or.hd=rs.getString(7);
                 or.graphiccard=rs.getString(9);
 
System.out.print(or.serial+cname+keyboard+monitor+mouse+printer+pro+ram+hd+graphiccard);

 
 

      } 
      catch (Exception e)
      {
          JOptionPane.showMessageDialog(this, e.getMessage());
      }
      eo.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sno=JOptionPane.showInputDialog("Enter Your Order's serial No to delete it.");
      
      try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/technocomputer","root","manager");
            Statement s=con.createStatement();
            
            ResultSet rs=s.executeQuery("select * from orders where srno="+sno);
           if(rs.next())
            {
            String q= "delete from orders where srno="+sno;
            s.executeUpdate(q);
            JOptionPane.showMessageDialog(this, "Deleted Successfully.", "Deleted",2); 
              
            }
          else 
           {
            JOptionPane.showMessageDialog(this, "No Such Order Found!", "Error",1); 
           
           }
      }
      catch (Exception e)
      {
          JOptionPane.showMessageDialog(this, e.getMessage());
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
